### ISSUE TITLE
Add a note about Windows

### ISSUE THREAD

**Issue by villares** [tabreturn/thonny-py5mode#1]
Cheers Tristan!

Maybe you might want to consider adding a note that at this point this installation process is not working on Windows :(

The reason is `noise` cannot be installed with `pip` on Windows.

I'm trying to do it with `conda`/`miniconda` and I'll report, but it adds a nasty layer of complexity.

Tentative instructions:

- Install miniconda https://docs.conda.io/en/latest/miniconda.html
- Open the "Command Prompt" terminal and  use `conda env create -n py5coding -f http://py5.ixora.io/install/py5_environment.yml`
- Change under Thonny Tools > Options... 
    - Under **interpreter** tab,  change to **Alternative interpreter**,  find the conda `py5coding` env.    
       (on Linux the env appears on Thonny, but it didn't on Windows for me, I found out and filled manually)
     - *I COULDN'T MAKE IT WORK :(* 
     - the plugin site-packages is different from the interpreter site-packages and I couldn't install the plug-in

**Comment by tabreturn** [comment]
Closing this issue.
