### ISSUE TITLE
Missing import for `get_python_lib`

### ISSUE THREAD

**Issue by aivarannamaa** [tabreturn/thonny-py5mode#15]
It looks like at https://github.com/tabreturn/thonny-py5mode/blob/57131aa9a2e2c1d45f9dd8601e1b36fda81c0790/thonnycontrib/thonny-py5mode/__init__.py#L148 name `get_python_lib` is not imported. I ended up in this branch while testing py5mode in a venv.

I could overcome the error by adding `from distutils.sysconfig import get_python_lib` before this line.

**Comment by tabreturn** [comment]
Thanks, @aivarannamaa. I've added this line.
