### ISSUE TITLE
pyde extension support

### ISSUE THREAD

**Issue by kemelzaidan** [tabreturn/thonny-py5mode#43]
I realized that Thonny doesn't recognize the syntax when opening a file with .pyde extension. It would be awesome if the extension supports opening pyde files since this is the default extension used be the Processing IDE when saving python sketches.

**Comment by tabreturn** [comment]
Thanks @kemelzaidan -- this was something I was thinking about. I'll add it to my to-do list 👍

**Comment by villares** [comment]
Cheers @kemelzaidan !

Would you like to propose a PR for this?
Thonny has a set of valid "Python Extensions" that would have to be extended by the plug-in. 
https://github.com/thonny/thonny/blob/f313dac04032d659d1daccda98f4cd9efcea7704/thonny/editors.py#L41

I see the utility of being able to open `.pyde` files on Thonny as I migrate and convert old Processing Python Mode sketches to py5, but, on the other hand, is it worth the trouble?

**Comment by kemelzaidan** [comment]
@villares took me forever, but I finally did it... https://github.com/thonny/thonny/pull/3303.

Let's wait and see now...

**Comment by villares** [comment]
As the issue became a Thonny PR, I think we can safely close this!
