### ISSUE TITLE
Plugin fails to load on Raspberry Pi

### ISSUE THREAD

**Issue by MarcScott** [tabreturn/thonny-py5mode#47]
Installed Thonny on both NixOS and on Raspberry Pi OS.
After installing thonny-py5mode and restarting Thonny, I get the following error

```
Warning: Failed loading plugin thonnycontrib.backend.py5_imported_mode_backend.
See backend.log for more info.
````

The p5 mode option does not appear in the menu bar.

**Comment by villares** [comment]
Cheers @MarcScott !

The thonny-py5mode plugin depends on the JDK install that is not prepared for Raspi and some other architectures, I'm afraid this could be the cause.

Can you try "manually" installing py5 and its dependencies in your Thonny to see if thing will work out?

In February I think tabreturn will be back working on the plug-in and I think we can explore this issue better...

**Comment by villares** [comment]
Hi @MarcScott could you make it work?  The install-jdk library will soon be able to handle Raspis, I'd like to know how it is going for you.

**Comment by gilfuser** [comment]
Hi there.

Same error message here while installing in the Raspberry Pi with Raspberry OS. The plugin is also not loading. Looking at the backend.log file, as suggested in the error message, I could find just this error:
```
ImportError: this version of pandas is incompatible with numpy < 1.20.3
your numpy version is 1.19.5.
Please upgrade numpy to >= 1.20.3 to use this pandas version
``` 
I manually upgraded to the newest numpy and installed JDK as @villares suggested, but the error persists. Searching result for `numpy` in the Plug-ins Manager reflects the upgrade (numpy 1.25.1), but the backend.log still reports the same error.

Python version is 3.9.2

**Comment by villares** [comment]
Cheers @gilfuser, can we try the Raspberry Pi again at some point? I think @claudefalbriard would also be interested, and we could schedule a video chat about it perhaps?

**Comment by gilfuser** [comment]
Hi @villares, that would be great!

Let's check our schedules to find out when.

I could do it either this afternoon or later tonight at 9 pm or so (GMT-3). I can also on Friday anytime.

Abraços,
Gil

**Comment by villares** [comment]
Just to report that yesterday, with @gilfuser , using the newest `install-jdk` library to install the JDK, and adding a missing NumPy component, it worked fine on the Raspberry Pi.

**Comment by villares** [comment]
Cheers @MarcScott !

I renamed the issue so it is a bit more descriptive.

As I have managed to make it work on the Raspberry Pi last year with my friend Gil and I haven't heard from you in after that I'm going to close this, but if you want to chat about it please ping me, and we can also re-open this issue.

**Comment by MarcScott** [comment]
Thanks @villares I'll test my end as well, but if it's working for you then happy for this to remain closed.
Cheers for all the hard work.
