### ISSUE TITLE
Not able run sketches on thonny py5 mode

### ISSUE THREAD

**Issue by jaivanti** [tabreturn/thonny-py5mode#48]
So, whenever I am trying to code a sketch in py5 in thonny, it throws a error that theres no module found. 
heres the snippet of the error: Warning: Failed loading plugin thonnycontrib.backend.py5_imported_mode_backend.
See backend.log for more info.
Traceback (most recent call last):
![image](https://user-images.githubusercontent.com/62715739/216278814-33957d8c-e3d0-40cd-852f-84e2c81d6e29.png)

**Comment by villares** [comment]
Hi @jaivanti, let's investigate this further!

It looks like the interpreter Thonny is using is not the same where py5 was installed, which is terrible, it happened to me a few times and it is very confusing.

So, please, tell me what operating system are you using? Windows, Linux or Mac?

How did you install Thonny, and which version of Python does it say down in the console before you start running your code?

Mine is like this:
![image](https://user-images.githubusercontent.com/3694604/218489962-4dfdfb9e-570a-4007-8ccd-f5e76995f527.png)

Another idea, if you are on Windows, can you test this "portable" Thonny with py5 installed?
https://www.dropbox.com/s/3ue4cx3yf372teg/thonny-4-with-py5-windows-portable.zip?dl=0

**Comment by jaivanti** [comment]
Hi @villares !
Thankyou so much for this. Its working! I have windows and had installed thonny from their website. The dropbox zip file works and am not getting any errors! Thanks alot!

**Comment by villares** [comment]
Hi @jaivanti ! I hope your py5 explorations are going well. 

I'm going to close this, but if you want to investigate the problem further we can re-open it. 

In that case I'd ask you to install a fresh copy of Thonny, then the py5 library with "Manage Packages...", then thonny-py5mode with the "Manage plug-ins..." panel. Stop and relaunch Thonny and try to check "Imported mode for Thonny" to see if it will install a JDK... 
Regards, Alexandre.
