### ISSUE TITLE
Not being able to run a sketch

### ISSUE THREAD

**Issue by marziabil** [tabreturn/thonny-py5mode#49]
Hi, 

I am getting the following error when I try to run a sketch: 

`def setup():
    size(300, 200)
    rect_mode(CENTER)

def draw():
    rect(mouse_x, mouse_y, 10, 10)`

![image](https://user-images.githubusercontent.com/94219257/221346028-de593df8-52f0-4387-bafa-456a9936d812.png)

Can you please tell me what the issue is?

Thanks in advance!

**Comment by tabreturn** [comment]
Thanks for the question, @marziabil. I assume you worked it out somehow. Let me know if there's anything important I should note.
