### ISSUE TITLE
JAVA_HOME environment variable

### ISSUE THREAD

**Issue by walterreiner** [tabreturn/thonny-py5mode#54]
Hi!, I am having problems with Py5 in Thonny.

py5 is unable to start a Java 17 Virtual Machine.
This library requires Java 17 to be installed and a properly set JAVA_HOME environment variable.
Here is some debug info about your installation that might help you identify the source of this problem.
{'JAVA_HOME environment variable': '/Users/-------/Library/Thonny/jdk-17', 'jvm version': (0, 0, 0), 'default jvm path': '/Users /-------/Library/Thonny/jdk-17/Contents/Home/lib/libjli.dylib'}

when I run java -version in terminal

java version "20.0.2" 2023-07-18
Java(TM) SE Runtime Environment (build 20.0.2+9-78)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.2+9-78, mixed mode, sharing)

I don't understand what to do, thanks for the help

**Comment by walterreiner** [comment]
Ok, i fix my problem folowing this amazing tutotrial

https://www.youtube.com/watch?v=-ecG6B_jNW8

So now its running, sorry for the issues.

Bye!

**Comment by villares** [comment]
Hi @walterreiner! Sorry to hear about your trouble. Let's see if we can get some help.
Meanwhile, can you confirm which OS are you running on? From the path I'd guess MacOS... 

Now I'm goingo tell things that helped me before... I'd ask you to check on Thonny 's menu `Tools > Options... > General` if you have something in "environment variables" like this:  (similar but different as I'm on Linux)

![image](https://github.com/tabreturn/thonny-py5mode/assets/3694604/f39d3142-a8b7-4e8e-afaf-a4ff0b0099e2)

If you have, can you check if it leads to a valid path/place with a JDK?
Can you change it so it points to a valid JDK path? Then you need to close and restart Thonny.

 (I wonder if it could even be pointing to your JRE 20 if you can find it, it might also work)

**Comment by walterreiner** [comment]
Hi Alexandre, its is working now!!! hao can i close the issue?

**Comment by villares** [comment]
I'll close it for you!

**Comment by hx2A** [comment]
Thank you, @villares , and @walterreiner , have fun programming with py5!
