### ISSUE TITLE
No JVM shared library file (jvm.dll) found

### ISSUE THREAD

**Issue by eduboni** [tabreturn/thonny-py5mode#9]
Hi, 

I'm trying to use Thonny to run a code that uses pymunk, but it gives an error "No JVM shared library file (jvm.dll) found".

I went to the C:\Users\Admin\AppData\Roaming\Thonny\ folder and confirmed that the JDK is installed (the jdk-17 folder is there).
I understand then that Thonny is not accessing the jdk folder... could this be the problem? Could you suggest a solution, please?

thanks

**Comment by tabreturn** [comment]
Hi @eduboni 

Which version of Thonny are you using?

Is this only using Pymunk? Can you run a plain-old py5 sketch? Like a `circle(10, 10, 10)`?
